### ISSUE TITLE
Chrome + extension + discord generating pw change requests after login

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#389]
### Expected behavior
Log in to discord website, all is well.

### Actual behavior
Log in to discord website through MPmini.  Once logged in get additional "Change password" requests appearing on MPmini.

### Step by step guide to reproduce the problem
Navigate to discord, log in via MPmini and extension, once logged in view "Change password" requests come up.

### Mooltipass version
Which Mooltipass do you use? MPmini (hand made from github resources)
What is its firmware version? 1.2 (Built from git, some options disabled)

**Comment by limpkin** [comment]
Aren't you getting additional "get password" requests? I've had this problem a while ago but didn't manage to reproduce it. 
What website are you using?

**Comment by kbembedded** [comment]
No, I am actually getting "Change password for..." requests, which is why this is so bizarre.

The webssite is discordapp.com which is the main page for the discord communication tool.

**Comment by limpkin** [comment]
OK ! We will investigate then.

**Comment by limpkin** [comment]
Hello there!

I've just pushed extension .78 to the store. Could you let me know if that solves your problem?
Also, you mentioned a while ago that you'd write up a "how to create a mini from scratch" guide... any progress on that front?

**Comment by kbembedded** [comment]
I've actually got 1.1.79 running right now, and I still see the problem occur.  

Navigate to https://discordapp.com/login and use MPmini to log in with extension.
Immediately a number of "Change Password" requests are generated.
If I got to settings, log out; and then navigate away from the tab and wait until "Change Password" requests all go away on the mini.
And then click back to the now login page (https://discordapp.com/login it auto redirected there upon log out), I again get further "Change Password" requests and no log in request.  I have to close the tab, and re-navigate to the login page in order to get a log in request again.

As for the guide, I am still working on it.  Two units are now in every-day use, and the third unit I have is currently in the hands of a friend who is working on a custom case, since all three of mine were made with a thicker PCB than the production units (this is something else I need to ensure is noted in the design files).  When I get that third unit back I will refine the instructions, confirm them with you (just in case you have ideas on making it easier), and get all of that pushed.  I also want to fix the PCB layout I have.  I currently am using a TagConnect cable (pinned out for a bus pirate, because I have no other Atmel programming tools), but on the PCB placed it in a rather dumb spot that is partially blocked by the smart card connector.  The fork in my repo has a couple of changes already pushed, will generate a PR when its done.

**Comment by limpkin** [comment]
Hello!

Do you still have the problem? I'm currently running 1.1.80 and can't reproduce this issue

**Comment by kbembedded** [comment]
I am actually still seeing this issue.  Using extension 1.1.80 and app 2.0.78 on Chrome 58.0.3029.110 (64-bit)  Not sure if the chrome version plays a role in this or not.  I'm not sure what else I can do.  I don't have a hardware USB analyzer, but I could probably find a half decent software version and send you the dump of it if you are interested?

**Comment by limpkin** [comment]
Hello,
I actually think it may be better if you could give us a console log by installing this repository chrome_extension folder manually on chrome.
Simply enable the developer mode in chrome://extensions/, click "load unpacked extension", select the folder, click on "background page" & the console tab.

**Comment by kbembedded** [comment]
Alright, I've done that, was able to reproduce it and got some log output.  I think I have sanitized this pretty well, user/pass gone, as well as some other unique IDs.  I tried to focus in on the relevant bits so let me know if you think anything is missing, or there is any text in here that would not be wise to paste online.
[strippedlog.txt](https://github.com/limpkin/mooltipass/files/1006394/strippedlog.txt)

**Comment by limpkin** [comment]
Hello,

could update your repo copy and try again now?

**Comment by kbembedded** [comment]
Okay, I've resolved it, but it in a very weird way.

Patch does not have any effect.  I then realized I had DISABLE_USB_CMD_CHECK_PASSWORD in my custom setup, still had no impact after updating the firmware without that option.  For shits and giggles, I deleted my credentials and re-created them.

I first output user/pass to a text file, so I could re-create the account in the MP when it was deleted.  I found that I could not log in with that password when I tried manually.  I then verified that I could log in via the plugin request.  Disabled the plugin, and attempted to log in to the website manually with the MP through "LOGIN."  I could not log in, it did not like my password.  I ran in to this when using the standalone windows application for discord, and just assumed it was a bug on their end.  

I deleted the credentials on the MP, went through a password request, used the plugin to make a new password (which, had some issues updating the credentials, and tried to make a blank account), ran through the cred. management mode to delete the blank account and move the password over.

I no longer get "Change password..." requests upon login through plugin prompt, and I can manually log in to the website and the application thought the MP device directly.

Any insight as to why this whole thing occurred?  That the plugin prompt login would work (and I guess still think I had an invalid pw), but manually it complained about an incorrect password.

I have since restored from the backup I made before trying this.  Changed my discord password back to the old one as coped from cred. management mode.  Now the opposite occurs.  I can log in manually, but any attempts through the plugin prompt fail with an invalid password.  And when I log in manually, I get a "Change password..." request on the MP device itself.

I then ran an integrity check, it claimed all was okay; but the above problem still persisted, I could log in manually, but through the plugin failed.  

You can probably close this, unless you want to further investigate.  It is incredibly weird and I have no idea how the unit got in to this state.

**Comment by limpkin** [comment]
hmmm any special characters in that password that may be filtered by the website ?

**Comment by kbembedded** [comment]
If there are, then their change password form is not properly checking that in the first place.

I'm more baffled by how the plugin request worked, and manual input didn't, and then when I restored it to try again, plugin request failed, but manual input worked.  I'm not familiar enough with the underlying data blob for each credential to know what is going on there exactly.

**Comment by limpkin** [comment]
is your computer slow? if so you may need to select the "add delay" feature to make sure all characters are properly output using manual password recall.

**Comment by kbembedded** [comment]
Computer is not slow.  But I do have delay enabled anyway (Use it for my android phone which does require a delay on input).  And even still, this issue has never shown up on any other website or application.

**Comment by limpkin** [comment]
hmm... I'm running out of ideas :/

**Comment by kbembedded** [comment]
No worries.  Thanks for the work you put in to trying to get to the bottom of it.  If I manage to recreate it in some way, I'll let you know.  Otherwise, I just attribute it to some hiccup.
