### ISSUE TITLE
Issue with Steam website

### ISSUE THREAD

**Issue by kbembedded** [limpkin/mooltipass#445]
### Expected behavior
Going to help.steampowered.com, logging in via manual MP entry (notes below), and then getting the Steam account guard popup.

MP steam account set up with store.steampowered.com, so help.steampowered.com does not auto-detect.  This is fine, but simply requires manual entry.  I also have the Steam guard set up through a smartphone, which creates timed keys that are used to verify login.

### Actual behavior
Upon submitting credentials through the MP to help.steampowered.com and pressing the log in button, the Steam website presents the Steam guard window, while the MP plugin produces a "Store credentials" popup, asking if if steampowered.com or help.steampowered.com should be use to store the credentials.

After the MP popups, the Steam guard popup changes, saying that it was an invalid entry.  Meaning somehow the MP app has tried to enter something.  Upon correct entry of Steam guard key, the website goes back to the login page and reports no failures.

In one situation, the MP app kept bringing up popups at this point, which caused Steam to think I was attempting to rapidly log in, and locking me out.

### Step by step guide to reproduce the problem
Windows 7
Chrome browser: Version 59.0.3071.115 (Official Build) (64-bit)
MP plugin: 1.1.82
MP app: 2.0.80
Steam Guard app set up on smartphone (Android used in this case, but I don't think it would matter.
Have credentials set up for Steam under "store.steampowered.com"
Follow steps above in "Actual Behavior" to get it to reproduce.

### Operating System
Windows 7

### Mooltipass Device
The Mooltipass Mini - Custom firmware based on MPmini release, with slight option changes.

**Comment by kbembedded** [comment]
Addendum:
Attempting to log in to store.steampowered.com will prompt MP extension and therefor MP itself to enter credentials.  When approved, credentials are entered and the login page resets.  I have seen and reported this behavior for other websites in the past as well.

Logging in requires disabling the MP extension, and using manual credential retrieval from the MP.

**Comment by Arffeh** [comment]
Can confirm; huge pain point.

The mooltipass especially makes a lot of sense to use with a steam account, when an account can have a lot of dollars worth of games ($6300 personally) with a metric ton of hours put in.

**Comment by limpkin** [comment]
Hello there,

We've recently pushed a newer version of our extension to our testers.
Would you be able to uninstall your chrome extension, and install our testers only version (1.1.84) here?
https://chrome.google.com/webstore/detail/mooltipass-extension/mkjlelalgdinanmcljpgkojjolkdcebh

Let us know if it now works better.
Thanks!

**Comment by kbembedded** [comment]
Ran through with new extension per your request.

It, sort of fixes the issue, but its definitely not a satisfying fix.  Rather than:
"After the MP popups, the Steam guard popup changes, saying that it was an invalid entry. Meaning somehow the MP app has tried to enter something. Upon correct entry of Steam guard key, the website goes back to the login page and reports no failures."

It now:
"After the MP popups, the Steam guard popup changes, saying that it was an invalid entry. Meaning somehow the MP app has tried to enter something. Upon correct entry of Steam guard key, login is complete"

It still does a false submit of the Steam guard key for 2FA, but a second submission is now accepted properly rather than booting the page back to the main login.

**Comment by limpkin** [comment]
i've just pushed .85 here : https://chrome.google.com/webstore/detail/mkjlelalgdinanmcljpgkojjolkdcebh 
Can you try again?

**Comment by kbembedded** [comment]
Sorry for the delay, have been out of town.

Currently using .89, and can confirm I still see the following:
"After the MP popups, the Steam guard popup changes, saying that it was an invalid entry. Meaning somehow the MP app has tried to enter something. Upon correct entry of Steam guard key, login is complete"

It still does a false submit of the Steam guard key for 2FA, but a second submission is now accepted properly rather than booting the page back to the main login.

**Comment by limpkin** [comment]
@reepush ; didn't we find that it was now normally working?

**Comment by reepush** [comment]
@limpkin 
Trying to reproduce this issue with no luck with extension installed from the store.

@kbembedded 

I follow this steps trying to reproduce this problem:
1. I go to https://store.steampowered.com/login
2. Enter credentials
3. Click on sign in button
4. Steam guard popup becomes visible
5. Enter code and submit it
6. Proceed to Steam successfully

Do you follow exact the same steps?

**Comment by kbembedded** [comment]
@reepush 

Take a close look at step 4 of yours.  The popup appears normally, then about a second later it turns in to a "Whoops.  Sorry but that isn't quite right" title, meaning a submission of a Steam guard code failed.  And the "enter" button changes to "I want to try again, and I've re-entered my authenticator code above"

If I enter the code at this point, it works and I can log in.  As it is now, this process works, but its a tad clunky and does submit a failed Steam guard code.

**Comment by reepush** [comment]
@kbembedded 
I tried to reproduce step 4 with no luck with 1.1.89 version and the one from master. I made a [short recording](https://www.dropbox.com/s/7eanazx630nkwbh/steam-login.mp4?dl=0) also. Could you make sure that you are running latest version from store (1.1.89 currently)? Video recording will also help to investigate this problem.

**Comment by kbembedded** [comment]
@reepush I have verified that with complete certainty, I have 1.1.89 running of the extension, and 2.0.81 of the app.  For reference again, this is in Windows 7, in chrome Version 60.0.3112.90 (Official Build) (64-bit).  I also made a separate and brand new account to test this with (because I have had weird account settings do weird things with the MP in the past) and was still able to reproduce the issue.

I too have made a small video, hope this helps.  Sorry its not the best quality.  I'm not really well set up for screen capture.  https://www.dropbox.com/s/h2ay46v3331p3cy/test.wmv?dl=0

Just an FYI, if you can't reproduce it, you can't reproduce it.  I understand how frustrating it is to address an issue that can't be reproduced.  As-is, I can log in (albeit with that oddity occurring) but I just wanted to make sure this is known.

**Comment by reepush** [comment]
@kbembedded 
Your recording is very helpful! I tested with Steam Guard with email authentication and you have mobile one. Fixing now, will be available in next release. Thanks!

**Comment by limpkin** [comment]
can you confirm this is solved with version 1.3.0?

**Comment by kbembedded** [comment]
Can confirm issue no longer exists in 1.3.0

Tested with 1.1.89 (latest in chrome extension library) and confirmed issue exists, then switched to 1.3.0 and verified it no longer does.  Thanks!
